cards redesigned
Quento-Solutions/Quento pull request #293
Opened 2020-09-02 20:16 UTC by Eshchock1

![image](https://user-images.githubusercontent.com/44539091/92032047-89da7100-ed37-11ea-9522-fd5bd0ef86e6.png)
![image](https://user-images.githubusercontent.com/44539091/92032060-8d6df800-ed37-11ea-9369-aed59c92a722.png)
![image](https://user-images.githubusercontent.com/44539091/92032086-99f25080-ed37-11ea-9732-cb5d33980efa.png)
![image](https://user-images.githubusercontent.com/44539091/92032090-9e1e6e00-ed37-11ea-9904-d6d00ca1ae91.png)

2020-09-02 23:27 UTC, DrCheddar requested changes
Overall looks really really good, I think we should do some space optimizations for mobile though to not make each card take up the entire screen. Other than that, just rebase and you are good

2020-09-02 23:27 UTC, DrCheddar commented on components/NotesCard.vue
> +
Can we remove the preview image on mobile? 
![image](https://user-images.githubusercontent.com/46302202/92047039-1560fb80-ed52-11ea-96bc-23ec80290aff.png)
takes up too much space

2020-09-02 23:27 UTC, DrCheddar commented on components/NotesCard.vue
> +
Also turn down the max-height on the md preview on mobile? 
![image](https://user-images.githubusercontent.com/46302202/92047084-2f9ad980-ed52-11ea-89b7-88c5564049da.png)
So either we show an image or md preview not both, saves alot of space

2020-09-02 23:29 UTC, DrCheddar commented on components/NotesCard.vue
> +
Also theres this issue with the menu dots 
![image](https://user-images.githubusercontent.com/46302202/92047220-93250700-ed52-11ea-9788-199cce87c16c.png)
![image](https://user-images.githubusercontent.com/46302202/92047236-9b7d4200-ed52-11ea-9d24-50bb7372ea54.png)

2020-09-03 16:12 UTC, picklepower24 requested changes
Looks good to me, code is neat. I agree with Jeffrey though, pictures take too much space on mobile.
![image](https://user-images.githubusercontent.com/68477910/92140141-b85f5700-edde-11ea-945b-60b571b7dca2.png)
Also, just an idea: maybe have different default images for each course? looks like the current green one could be for chem.

2020-09-03 16:20 UTC, Eshchock1 commented
![image](https://user-images.githubusercontent.com/44539091/92140909-ba75e580-eddf-11ea-8665-923c5b15871b.png)
![image](https://user-images.githubusercontent.com/44539091/92140966-cd88b580-eddf-11ea-8de1-07d7d7cbc754.png)

2020-09-03 16:39 UTC, picklepower24 submitted a review, later dismissed
Some images seem to be broken on older notes, but I like the new image height.
![image](https://user-images.githubusercontent.com/68477910/92142910-88b24e00-ede2-11ea-8248-cb55956aab43.png)

2020-09-03 21:09 UTC, DrCheddar approved these changes
Looks fucking good

2020-09-03 21:14 UTC, merged