Followers
Quento-Solutions/Quento pull request #321
Opened 2020-09-06 05:58 UTC by Vansh-Sethi

You now have the ability to follow users!
![image](https://user-images.githubusercontent.com/44345210/92319288-6851e180-efe4-11ea-9d98-8a50bb254605.png)
![image](https://user-images.githubusercontent.com/44345210/92319296-743da380-efe4-11ea-96ad-f11bb68c5212.png)

2020-09-06 16:15 UTC, picklepower24 requested changes
Crashes.
![image](https://user-images.githubusercontent.com/68477910/92330139-ab3ea400-f03a-11ea-9d5d-9e81766a9e55.png)

2020-09-07 14:59 UTC, picklepower24 requested changes
No ability to cancel follow request. However, the rest of the functionality seems OK.
![image](https://user-images.githubusercontent.com/68477910/92399888-0505a380-f0f9-11ea-9825-35fd80c34596.png)
However, the "Friends" list shows users twice if they follow you but your follow is still pending.
![image](https://user-images.githubusercontent.com/68477910/92399986-26668f80-f0f9-11ea-807c-5c2770abffc2.png)

2020-09-07 16:59 UTC, picklepower24 requested changes
Would it be possible to split this list into two buttons? One to show followers and one to show following? Also, is there any functionality that comes with following yet (private posts)?
![image](https://user-images.githubusercontent.com/68477910/92407857-da701680-f109-11ea-87ce-5a500dde1a7d.png)

2020-09-07 17:54 UTC, DrCheddar approved these changes

2020-09-07 17:56 UTC, merged